### ISSUE TITLE
思路还是有值得学习的地方，如果一个控件本身有 Background ，那该如何设置该控件的阴影效果呢？

### ISSUE THREAD

**Issue by lijiankun24** [JuHonggang/ShadowDrawable#1]

**Comment by MahatmaSun** [comment]
现有情况 你可以套个父view 然后给父view加阴影 哈哈.

**Comment by Liberuman** [comment]
@lijiankun24 目前支持设置圆形，圆角，渐变等方式的背景，只需要传入相应的属性即可。其他类型的背景使用较少，所以暂未支持，如果有需求，MahatmaSun的方案倒是可取的。
