### ISSUE TITLE
假如只需要一边是阴影呢

### ISSUE THREAD

**Issue by awu515** [JuHonggang/ShadowDrawable#4]
比如，只需要上面是阴影

**Comment by lijiankun24** [comment]
看看说明文档，里面有写

**Comment by Liberuman** [comment]
@awu515 阴影的实现就是绘制的矩形，所以严格的单边是不支持的，但你可通过设置为显示阴影的一边增加padding以突出其阴影效果。

**Comment by awu515** [comment]
已实现只需要顶部阴影效果，要小改下那个阴影矩形的参数。谢谢提醒。
