### ISSUE TITLE
布局里面包裹了视频控件

### ISSUE THREAD

**Issue by xwsm** [JuHonggang/ShadowDrawable#6]
然后视频播放不了。。。。。

**Comment by Liberuman** [comment]
@xwsm 直接给视频组件设置背景会导致视频被遮盖，可用下面的方式试一下：

`

        <FrameLayout
            android:layout_width="wrap_content"
            android:layout_height="300dp"
            android:layout_marginTop="24dp">
            <View
                android:id="@+id/video_bg_view"
                android:layout_width="120dp"
                android:layout_height="210dp"
                android:padding="5dp"
                android:layout_gravity="center"
                android:visibility="visible"/>
            <VideoView
                android:id="@+id/video_view"
                android:layout_width="200dp"
                android:layout_height="200dp"
                android:layout_gravity="center"
                android:visibility="visible"/>
        </FrameLayout>
`

然后给video_bg_view空间设置带阴影的背景。

**Comment by xwsm** [comment]
可以，感谢@JuHonggang
